# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lqprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
