# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:40
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170822_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lqprofile',
            name='avatar',
            field=models.ImageField(blank=True, default=b'avatar_male.png', upload_to=authentication.models.photo_upload_path),
        ),
        migrations.AlterField(
            model_name='lqprofile',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lqprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
