# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 11:44
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170918_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lqprofile',
            name='avatar',
            field=models.ImageField(blank=True, default=b'avatar_male.png', null=True, upload_to=authentication.models.photo_upload_path),
        ),
    ]
