# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20170920_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='lqprofile',
            name='has_photo',
            field=models.BooleanField(default=False),
        ),
    ]
